# 🚀 진짜 필수만 - GitHub Actions
# 내부 테스트는 철저하고 꼼꼼하게, GitHub Actions는 진짜 필수만

name: Essential Only CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

# 동시 실행 제한
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # 기본 검증만 수행 (1-2분 이내 완료)
  quick-validation:
    name: "⚡ 빠른 검증"
    runs-on: ubuntu-latest
    timeout-minutes: 3
    
    steps:
    # 1. 체크아웃
    - name: 📥 코드 체크아웃
      uses: actions/checkout@v4
      
    # 2. Python 설정 (캐시 사용)
    - name: 🐍 Python 설정
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: 'pip'
        
    # 3. 최소 의존성만 설치
    - name: 📦 최소 의존성 설치
      run: |
        python -m pip install --upgrade pip
        pip install black isort flake8
        
    # 4. 진짜 필수만 - 문법 체크
    - name: 🔍 진짜 필수 - 문법만
      run: |
        python -m py_compile src/core_engine/main.py
        echo "✅ 핵심 문법 OK"
        
    # 5. 진짜 필수만 - 보안 체크  
    - name: 🔒 진짜 필수 - 보안만
      run: |
        if grep -r "api_key.*=.*['\"][a-zA-Z0-9]\{20,\}['\"]" src/ --include="*.py" 2>/dev/null; then
          echo "❌ 하드코딩된 키 발견"
          exit 1
        fi
        echo "✅ 보안 OK"
        
    # 6. 완료
    - name: ✅ 완료
      run: |
        echo "✅ GitHub Actions: 진짜 필수만 완료!"
        echo "💡 철저한 테스트는 로컬에서: ./scripts/test_local.sh"